//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRLab.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class E00T_Customer_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E00T_Customer_Item()
        {
           
        }
        public E00T_Customer_Item(long contactID, string address, string contactName, string customerCode, string email, string note)
        {
            this.contactID = contactID;
            this.address = address;
            this.contactName = contactName;
            this.customerCode = customerCode;
            this.email = email;
            this.note = note;
        }

        [Key]
        public long contactID { get; set; }
        public string customerCode { get; set; }
        public string contactName { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string note { get; set; }
        [ForeignKey("customerCode")]
        public virtual E00T_Customer E00T_Customer { get; set; }
    }
}
