//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRLab.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class E00T_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E00T_Customer()
        {
            this.E00T_Customer_Item = new HashSet<E00T_Customer_Item>();
            this.E08T_AnalysisRequest_Info = new HashSet<E08T_AnalysisRequest_Info>();
        }

        public E00T_Customer(string city, string companyAddress, string companyName, string contactEmail, string contactName, string customerCode, string note)
        {
            this.city = city;
            this.companyAddress = companyAddress;
            this.companyName = companyName;
            this.contactEmail = contactEmail;
            this.contactName = contactName;
            this.customerCode = customerCode;
            this.note = note;
        }

        [Key]
        public string customerCode { get; set; }
        public string companyName { get; set; }
        public string contactName { get; set; }
        public string contactEmail { get; set; }
        public string companyAddress { get; set; }
        public string city { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E00T_Customer_Item> E00T_Customer_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E08T_AnalysisRequest_Info> E08T_AnalysisRequest_Info { get; set; }
    }
}
