//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRLab.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class E08T_Testing_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E08T_Testing_Data() { 

        }

        public E08T_Testing_Data(long? iD, string lOD, long? matrixID, double max, double min, double precision, long? specID)
        {
            this.iD = iD;
            LOD = lOD;
            this.matrixID = matrixID;
            this.max = max;
            this.min = min;
            this.precision = precision;
            this.specID = specID;
        }
        [Key]
        public Nullable<long> iD { get; set; }
        public Nullable<long> matrixID { get; set; }
        public Nullable<long> specID { get; set; }
        public double min { get; set; }
        public double max { get; set; }
        public double precision { get; set; }
        public string LOD { get; set; }
        [ForeignKey("matrixID")]
        public virtual E00T_SampleMatrix E00T_SampleMatrix { get; set; }
        [ForeignKey("specID")]
        public virtual E00T_Specification E00T_Specification { get; set; }
    }
}
