//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRLab.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class E08T_AnalysisRequest_Data
    {
        public string requestNo { get; set; }
        public string LVNCode { get; set; }
        public string analysisCode { get; set; }
        public string sampleMatrix { get; set; }
        public string specification { get; set; }
        public string method { get; set; }
        public Nullable<double> min { get; set; }
        public Nullable<double> max { get; set; }
        public Nullable<double> precision { get; set; }
        public string unit { get; set; }
        public string LOD { get; set; }
        public Nullable<int> urgentRate { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> turnAroundDay { get; set; }
        public string specMark { get; set; }
    
        public virtual E08T_AnalysisRequest_Item E08T_AnalysisRequest_Item { get; set; }
    }
}
