//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRLab.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("E08T_AnalysisRequest_Info")]
    public partial class E08T_AnalysisRequest_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E08T_AnalysisRequest_Info()
        {
            this.E08T_AnalysisRequest_Item = new HashSet<E08T_AnalysisRequest_Item>();
        }
     
        public E08T_AnalysisRequest_Info(string requestNo, int? status, string testReportContactID, long? contactID, string customerID, DateTime? dateOfSendingResult, string note, int? numberSample, bool? orderConfim, string priceID, int? printVAT, DateTime? receivceDate)
        {
            this.requestNo = requestNo;
            this.status = status;
            this.testReportContactID = testReportContactID;
            this.contactID = contactID;
            this.customerID = customerID;
            this.dateOfSendingResult = dateOfSendingResult;
            this.note = note;
            this.numberSample = numberSample;
            this.orderConfim = orderConfim;
            this.priceID = priceID;
            this.printVAT = printVAT;
            this.receivceDate = receivceDate;
        }

        [Key]
        public string requestNo { get; set; }
        public string customerID { get; set; }
        public Nullable<System.DateTime> receivceDate { get; set; }
        public Nullable<System.DateTime> dateOfSendingResult { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> orderConfim { get; set; }
        public Nullable<long> contactID { get; set; }
        public string testReportContactID { get; set; }
        public Nullable<int> numberSample { get; set; }
        public Nullable<int> printVAT { get; set; }
        public string priceID { get; set; }
        public string note { get; set; }
        [ForeignKey("customerID")]

        public virtual E00T_Customer E00T_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E08T_AnalysisRequest_Item> E08T_AnalysisRequest_Item { get; set; }
    }
}
